platform :watchos, '6.0'
install! 'cocoapods', :deterministic_uuids => false

target 'TSColorWheel Example WatchKit App' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'TSColorWheel', :path => '../'

  target 'TSColorWheel Example WatchKit Extension' do
      inherit! :complete
  end
end
